"""
Very useful configuration management utilities, with some classes and functions generated by CodeX.
"""

import yaml
import os
from typing import Dict, Any, Optional, List
from ruamel.yaml import YAML


class Config:
    """Configuration manager for the project."""
    
    def __init__(self, config_path: Optional[str] = None):
        """
        Initialize configuration manager.
        
        Args:
            config_path: Path to configuration file. If None, uses default config.
        """
        if config_path is None:
            config_path = os.path.join(os.path.dirname(__file__), "../../configs/default_config.yaml")
        
        self.config_path = config_path
        self.yaml = YAML()
        self.yaml.preserve_quotes = True
        self.yaml.width = 4096
        self.config = self._load_config()
    
    def _load_config(self) -> Dict[str, Any]:
        """Load configuration from YAML file with inheritance support."""
        try:
            with open(self.config_path, 'r') as file:
                config = self.yaml.load(file)
            
            # Handle inheritance if 'extends' key is present
            if isinstance(config, dict) and 'extends' in config:
                config = self._load_with_inheritance(config)
            return config
        
        except Exception as e:
            raise ValueError(f"Error parsing YAML configuration: {e}")
    
    def _load_with_inheritance(self, config: Dict[str, Any]) -> Dict[str, Any]:
        """Load configuration with inheritance from parent configs."""
        extends = config.pop('extends', [])
        
        # Ensure extends is a list
        if isinstance(extends, str):
            extends = [extends]
        
        # Start with empty config
        merged_config = {}
        
        # Load parent configs in order
        for parent_path in extends:
            parent_config = self._load_parent_config(parent_path)
            merged_config = self._deep_merge(merged_config, parent_config)
        
        # Merge with current config (current config takes precedence)
        merged_config = self._deep_merge(merged_config, config)
        
        return merged_config
    
    def _load_parent_config(self, parent_path: str) -> Dict[str, Any]:
        """Load a parent configuration file."""
        if not os.path.isabs(parent_path):
            # Get directory of current config file
            current_dir = os.path.dirname(self.config_path)
            parent_path = os.path.join(current_dir, parent_path)
        
        if not os.path.exists(parent_path):
            raise FileNotFoundError(f"Configuration file not found: {parent_path}")
        temp_config = Config(parent_path)
        return temp_config.config
    
    def _deep_merge(self, base: Dict[str, Any], override: Dict[str, Any]) -> Dict[str, Any]:
        """Deep merge two dictionaries, with override taking precedence."""
        result = base.copy()
        
        for key, value in override.items():
            if key in result and isinstance(result[key], dict) and isinstance(value, dict):
                result[key] = self._deep_merge(result[key], value)
            else:
                result[key] = value
        
        return result
    
    def get(self, key: str, default: Any = None) -> Any:
        """
        Get configuration value using dot notation.
        
        Args:
            key: Configuration key (e.g., 'model.name', 'training.epochs')
            default: Default value if key not found
            
        Returns:
            Configuration value
        """
        keys = key.split('.')
        value = self.config
        
        try:
            for k in keys:
                value = value[k]
            return value
        except (KeyError, TypeError):
            return default
    
    def set(self, key: str, value: Any) -> None:
        """
        Set configuration value using dot notation.
        
        Args:
            key: Configuration key (e.g., 'model.name', 'training.epochs')
            value: Value to set
        """
        keys = key.split('.')
        config = self.config
        
        for k in keys[:-1]:
            if k not in config:
                config[k] = {}
            config = config[k]
        
        config[keys[-1]] = value
    
    def save(self, path: Optional[str] = None) -> None:
        """
        Save configuration to YAML file.
        
        Args:
            path: Path to save configuration. If None, saves to original path.
        """
        save_path = path or self.config_path
        
        # Create directory if it doesn't exist
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        
        with open(save_path, 'w') as file:
            self.yaml.dump(self.config, file)
    
    def update(self, updates: Dict[str, Any]) -> None:
        """
        Update configuration with new values.
        
        Args:
            updates: Dictionary of updates to apply
        """
        def _update_dict(d, u):
            for k, v in u.items():
                if isinstance(v, dict):
                    d[k] = _update_dict(d.get(k, {}), v)
                else:
                    d[k] = v
            return d
        
        self.config = _update_dict(self.config, updates)
    
    def validate(self) -> bool:
        """
        Validate configuration parameters.
        
        Returns:
            True if configuration is valid, False otherwise
        """
        required_keys = [
            'dataset.name',
            'dataset.data_dir',
            'model.name',
            'model.num_classes',
            'training.epochs',
            'training.learning_rate'
        ]
        
        for key in required_keys:
            if self.get(key) is None:
                print(f"Missing required configuration: {key}")
                return False
        
        # Validate dataset name
        valid_datasets = ['new_inbreast']
        if self.get('dataset.name') not in valid_datasets:
            print(f"Invalid dataset name. Must be one of: {valid_datasets}")
            return False
        
        # Validate model name
        valid_models = ['resnet18', 'resnet34', 'resnet50', 'resnet101']
        model_name = self.get('model.name')
        
        # Check if it's a valid model or a swin transformer v2 model
        if (model_name not in valid_models):
            print(f"Invalid model name.")
            return False
        
        return True
    
    def __str__(self) -> str:
        """String representation of configuration."""
        from io import StringIO
        output = StringIO()
        self.yaml.dump(self.config, output)
        return output.getvalue()


def load_config(config_path: Optional[str] = None) -> Config:
    """
    Load configuration from file.
    
    Args:
        config_path: Path to configuration file
        
    Returns:
        Config object
    """
    return Config(config_path)


def create_experiment_config(base_config_path: str, experiment_name: str, 
                           updates: Dict[str, Any]) -> Config:
    """
    Create a new configuration for an experiment based on a base config.
    
    Args:
        base_config_path: Path to base configuration file
        experiment_name: Name of the experiment
        updates: Dictionary of updates to apply
        
    Returns:
        New Config object
    """
    config = Config(base_config_path)
    config.update(updates)
    
    # Set experiment name
    config.set('project.name', f"{config.get('project.name')}_{experiment_name}")
    
    return config


def create_inherited_config(extends: List[str], overrides: Dict[str, Any] = None, 
                          base_dir: str = None) -> Config:
    """
    Create a configuration that inherits from multiple base configs.
    
    Args:
        extends: List of paths to base configuration files to inherit from
        overrides: Dictionary of overrides to apply after inheritance
        base_dir: Base directory for resolving relative paths (defaults to configs dir)
        
    Returns:
        New Config object with inherited configuration
    """
    if base_dir is None:
        base_dir = os.path.join(os.path.dirname(__file__), "../../configs")
    
    resolved_extends = []
    for path in extends:
        if not os.path.isabs(path):
            resolved_path = os.path.join(base_dir, path)
        else:
            resolved_path = path
        resolved_extends.append(resolved_path)
    
    temp_config = {'extends': resolved_extends}
    if overrides:
        temp_config.update(overrides)
    
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.yaml', delete=False) as f:
        yaml.dump(temp_config, f)
        temp_path = f.name
    
    try:
        config = Config(temp_path)
        return config
    finally:
        os.unlink(temp_path)
